### ISSUE TITLE
Issues in storage api spec

### ISSUE THREAD

**Issue by erezmus** [libero/shared-services-experiment#14]
While building the GraphQL upload client, I noticed a few issues:

1) In the type `FileMeta`, we have the `id` field as required. Since we are using the FileMeta for the `uploadFile` mutation, we would need to generate it on the client too? Same thing for `updated`.

We should either make those fields optional or separate it into two types, one for input and one as output

2) In REST the namespace is specified as part of the path, eg: 
`PUT /files/namespace/directory/file.ext`
but what should happen if say we send:
`PUT /files/file.ext`

Should it error 500? What about in GraphQL?

3) Is the `id` field in GraphQL the equivalent of the Rest `ETag` ?

**Comment by giorgiosironi** [comment]
> we have the `id` field as required [...] we would need to generate it on the client too?

It's possible to generate unique ids on clients as it helps idempotence if you retry the request. However we are dealing with that using the file path.

> Same thing for `updated`

That wouldn't make sense on the client.

> PUT /files/file.ext

I would expect this to fail with an error like "`file.ext` is not a defined namespace" as namespaces needs to be configured out of band in the service.

**Comment by NuclearRedeye** [comment]
On point 2, my thoughts are that all files should belong to a namespace and as such trying to PUT a file to the '/files' path should produce a HTTP 405 Method not allowed. That doesn't consider however how namespaces might be created, which if we need to be able to create them atomically should support the PUT method, in which case stricter validation of the ':namespaceId' should be put in place.

**Comment by erezmus** [comment]
Closing via #37
