### ISSUE TITLE
Should we use an OTS storage service?

### ISSUE THREAD

**Issue by diversemix** [libero/shared-services-experiment#16]

**Comment by diversemix** [comment]
@giorgiosironi / @GiancarloFusiello ... am I right in thinking that the only suitable one was minio and seeing that does not have the ability to query by metadata then we can answer this question with a "No"?

/cc @hdrury1

**Comment by hdrury1** [comment]
Also my understanding. Closing off.

**Comment by giorgiosironi** [comment]
Yes on both: the only suitable one was MinIO and it does lack features defined in the [common scope](https://docs.google.com/document/d/1C3ribQrYqX1OHrydee3kRjvhPvF4mYTLPQD78sUK4UY).

The more important question has become whether a shared Storage Service that implements the common scope is a good choice, working on refining the Publisher requirements.
