### ISSUE TITLE
Investigate Envoy to connect to a Configuration Service

### ISSUE THREAD

**Issue by giorgiosironi** [libero/shared-services-experiment#28]
Envoy is an open source edge and service proxy, designed for cloud-native applications.

Higher-level projects (Istio and Ambassador) should so be evaluated, since they abstract the deployment of Envoy itself. They may or may not be in scope for what we want to achieve, which is to connect a Storage Service and a Configuration Service together.

The output of this investigation should probably be a Google Docs document, as Github comments are not a good medium to collect and reorganize disparate information about architectures and tools.

### Running it

- [ ] What is the relationship with [Ambassador](https://www.getambassador.io/)?
- [ ] What is the relationship with [Istio](https://istio.io/docs/concepts/what-is-istio/)?
- [ ] Can these abtractions be run without Kubernetes or is it a hard requirement?
- [ ] what is the footprint of the project? Which containers need to run in a centralized place and/or inside Pods?
- [ ] what is the [deployment type](https://www.envoyproxy.io/docs/envoy/latest/intro/deployment_types/deployment_types) that we are interested in?

### Configuration

As far as I understand Envoy does not provide a storage for service-specific configuration. If correct, it means it can connect services (e.g. Storage Service) to a Configuration Service.

- [ ] how can the Storage Service discover where the Configuration Service is? Meaning not being configured with a hardcoded internal ip or hostname, but somehow connecting to it through the service mesh.
- [ ] how can authentication be performed so that only the Storage Service can connect to the Configuration Service rather than anything in the cluster?
- [ ] what sort of encryption, if any, can be provided on the connection, and how? e.g. HTTPS vs. leaving it to the underlying services
- [ ] compare the features previously mentioned with a (probably) lighter weight solution like [Consul](https://www.consul.io/intro/vs/proxies.html)

**Comment by giorgiosironi** [comment]
[Comparison](https://www.consul.io/intro/vs/istio.html) of Consul (evaluated for the Configuration Service before proposing etcd) and Istio, from the Consul documentation.

**Comment by diversemix** [comment]
@giorgiosironi / @GiancarloFusiello ... I would like to see this compared / contrasted with consul.io

There is an interesting article here: https://www.consul.io/intro/vs/proxies.html about the differences.

Also a more general comparison between the technologies here: https://kubedex.com/istio-vs-linkerd-vs-linkerd2-vs-consul/

**Comment by giorgiosironi** [comment]
Added Consul comparison to the checklist.

**Comment by GiancarloFusiello** [comment]
Here's the Google Doc I'm working on where I try to answer these questions: https://docs.google.com/document/d/1sR6poHv1LVECltAuTjC_7kCt_Z0fkv-RwZfyA7C61iw/edit?usp=sharing

I've added as much relevant information as I thought necessary but there's too much information to add into a google doc that the solution providers already have on their product websites, presented in a manner that is easy to navigate. Happy to add more information if needed.

**Comment by thewilkybarkid** [comment]
Don't know anything about it, but AWS App Mesh looks to be a hosted Envoy?

**Comment by hdrury1** [comment]
Closing as investigation complete; findings in Google Doc for perusal.

**Comment by giorgiosironi** [comment]
> AWS App Mesh looks to be a hosted Envoy

Envoy being a proxy that works on the data plane and is deployed dozens of times along the various services to connect them together, looks more like a proprietary hosted Istio (with a control plane allowing the configuration of the various Envoys) than a single hosted Envoy.
