### ISSUE TITLE
Which OTS Configuration service could be used?

### ISSUE THREAD

**Issue by diversemix** [libero/shared-services-experiment#4]
TBD

**Comment by giorgiosironi** [comment]
1. What are the keys that the Storage Service is going to read from here?
2. If the Configuration Service is not running or slow, is the Storage Service affected by that?
3. What library/sidecar/script is needed to read keys inside the Storage Service?

**Comment by diversemix** [comment]
@Cooryd / @petereast 
1. What are the keys that the Storage Service is going to read from here?

**Comment by diversemix** [comment]
We've come up with an example structure for the config

https://docs.google.com/document/d/1Ao-tZA9vFtaGxzURpaTotehHhAwODV2cQEG5IPfmYYM/edit?usp=sharing

**Comment by diversemix** [comment]
Discussed and decided to go with the more simple `etcd` ... also discussed deployment options and decided eventually the use of a sidecar service with a shared volume will be best. This is so that the associated service is not dependant on the config service implementation - rather it uses the local file from the volume that is written by the sidecar.

**Comment by diversemix** [comment]
ref: #15
